actioning some more

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -15,131 +15,134 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    - name: Installing poetry
+      run: pipx install poetry
     - name: Set up Python ${{ env.PYTHON_VERSION }}
       uses: actions/setup-python@v4
       with:
         python-version: ${{ env.PYTHON_VERSION }}
+        cache: 'poetry'
     
-    - name: Install Poetry
-      run: |
-        pip install --upgrade pip
-        pip install poetry
-        echo "POETRY_PATH=$(which poetry)" >> $GITHUB_ENV
-        echo "SITE_PACKAGES_PATH=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV
+    # - name: Install Poetry
+    #   run: |
+    #     pip install --upgrade pip
+    #     pip install poetry
+    #     echo "POETRY_PATH=$(which poetry)" >> $GITHUB_ENV
+    #     echo "SITE_PACKAGES_PATH=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV
 
-    - name: Cache Poetry installation and dependencies
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.cache/pypoetry
-          ${{ env.POETRY_PATH }}
-          ${{ env.SITE_PACKAGES_PATH }}
-        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+    # - name: Cache Poetry installation and dependencies
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: |
+    #       ~/.cache/pypoetry
+    #       ${{ env.POETRY_PATH }}
+    #       ${{ env.SITE_PACKAGES_PATH }}
+    #     key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
     
-    - name: Install dependencies
-      run: poetry install
+    # - name: Install dependencies
+    #   run: poetry install
     
-  test1:
-    needs: setup
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ env.PYTHON_VERSION }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    - name: Cache Poetry dependencies
-      id: cache-test
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.cache/pypoetry
-          ${{ env.POETRY_PATH }}
-          ${{ env.SITE_PACKAGES_PATH }}          
-        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
-    - name: Install Poetry
-      run: |
-        if [ "${{ steps.cache-test.outputs.cache-hit }}" == "true" ]; then
-            echo "Cache hit, checking Poetry installation"
-            poetry --version || echo "Poetry not found in cache"
-        else
-            echo "Cache miss, installing Poetry"
-            pip install poetry
-        fi
+  # test1:
+  #   needs: setup
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ env.PYTHON_VERSION }}
+  #     uses: actions/setup-python@v4
+  #     with:
+  #       python-version: ${{ env.PYTHON_VERSION }}
+  #   - name: Cache Poetry dependencies
+  #     id: cache-test
+  #     uses: actions/cache@v3
+  #     with:
+  #       path: |
+  #         ~/.cache/pypoetry
+  #         ${{ env.POETRY_PATH }}
+  #         ${{ env.SITE_PACKAGES_PATH }}          
+  #       key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+  #   - name: Install Poetry
+  #     run: |
+  #       if [ "${{ steps.cache-test.outputs.cache-hit }}" == "true" ]; then
+  #           echo "Cache hit, checking Poetry installation"
+  #           poetry --version || echo "Poetry not found in cache"
+  #       else
+  #           echo "Cache miss, installing Poetry"
+  #           pip install poetry
+  #       fi
 
-    - name: Run Tests
-      env:
-        DJANGO_SETTINGS_MODULE: django_unchained.settings
-      run: python -m poetry run ./manage.py test
+  #   - name: Run Tests
+  #     env:
+  #       DJANGO_SETTINGS_MODULE: django_unchained.settings
+  #     run: python -m poetry run ./manage.py test
         
-  test2:
-    needs: setup
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ env.PYTHON_VERSION }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    - name: Cache Poetry dependencies
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.cache/pypoetry
-          ${{ env.POETRY_PATH }}
-          ${{ env.SITE_PACKAGES_PATH }}          
-        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
-    - name: Install Poetry
-      run: pip install poetry
-    - name: Run Tests 2
-      env:
-        DJANGO_SETTINGS_MODULE: django_unchained.settings
-      run: python -m poetry run ./manage.py test
+  # test2:
+  #   needs: setup
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ env.PYTHON_VERSION }}
+  #     uses: actions/setup-python@v4
+  #     with:
+  #       python-version: ${{ env.PYTHON_VERSION }}
+  #   - name: Cache Poetry dependencies
+  #     uses: actions/cache@v3
+  #     with:
+  #       path: |
+  #         ~/.cache/pypoetry
+  #         ${{ env.POETRY_PATH }}
+  #         ${{ env.SITE_PACKAGES_PATH }}          
+  #       key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+  #   - name: Install Poetry
+  #     run: pip install poetry
+  #   - name: Run Tests 2
+  #     env:
+  #       DJANGO_SETTINGS_MODULE: django_unchained.settings
+  #     run: python -m poetry run ./manage.py test
 
-  test3:
-    needs: setup
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ env.PYTHON_VERSION }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    - name: Cache Poetry dependencies
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.cache/pypoetry
-          ${{ env.POETRY_PATH }}
-          ${{ env.SITE_PACKAGES_PATH }}
-        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
-    - name: Install Poetry
-      run: pip install poetry
-    - name: Run Tests 2
-      env:
-        DJANGO_SETTINGS_MODULE: django_unchained.settings
-      run: python -m poetry run ./manage.py test
+  # test3:
+  #   needs: setup
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ env.PYTHON_VERSION }}
+  #     uses: actions/setup-python@v4
+  #     with:
+  #       python-version: ${{ env.PYTHON_VERSION }}
+  #   - name: Cache Poetry dependencies
+  #     uses: actions/cache@v3
+  #     with:
+  #       path: |
+  #         ~/.cache/pypoetry
+  #         ${{ env.POETRY_PATH }}
+  #         ${{ env.SITE_PACKAGES_PATH }}
+  #       key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+  #   - name: Install Poetry
+  #     run: pip install poetry
+  #   - name: Run Tests 2
+  #     env:
+  #       DJANGO_SETTINGS_MODULE: django_unchained.settings
+  #     run: python -m poetry run ./manage.py test
 
-  test4:
-    needs: setup
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ env.PYTHON_VERSION }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ env.PYTHON_VERSION }}
-    - name: Cache Poetry dependencies
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.cache/pypoetry
-          ${{ env.POETRY_PATH }}
-          ${{ env.SITE_PACKAGES_PATH }}          
-        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
-    - name: Install Poetry
-      run: pip install poetry
-    - name: Run Tests 2
-      env:
-        DJANGO_SETTINGS_MODULE: django_unchained.settings
-      run: python -m poetry run ./manage.py test
+  # test4:
+  #   needs: setup
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ env.PYTHON_VERSION }}
+  #     uses: actions/setup-python@v4
+  #     with:
+  #       python-version: ${{ env.PYTHON_VERSION }}
+  #   - name: Cache Poetry dependencies
+  #     uses: actions/cache@v3
+  #     with:
+  #       path: |
+  #         ~/.cache/pypoetry
+  #         ${{ env.POETRY_PATH }}
+  #         ${{ env.SITE_PACKAGES_PATH }}          
+  #       key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+  #   - name: Install Poetry
+  #     run: pip install poetry
+  #   - name: Run Tests 2
+  #     env:
+  #       DJANGO_SETTINGS_MODULE: django_unchained.settings
+  #     run: python -m poetry run ./manage.py test
